import { useCallback, useEffect, useState } from 'react';
import Head from 'next/head';
import { GetServerSideProps } from 'next';
import { getSession, useSession } from 'next-auth/react';
import { Session } from 'next-auth';

import Card from '@/component/card';
import Loading from '@/component/loading';
import Form from '@/component/form';
import Header from '@/component/header';
import ErrorMessage from '@/component/error-message';

import { api } from '@/services/api';

import styles from '@/styles/Home.module.scss';

type MoviesEmojizadosType = {
  data: {
    movieName: string;
    movieEmojizado?: string;
  }
};

export type MoviesGeneratedCountType = {
  countMovies: number;
  maxMovies: number;
};

export interface CustomSessionProps extends Session {
  userActive: string;
};

export default function Home() {
  const [ loading, setLoading ] = useState(false);
  const [ isLoadingData, setIsLoadingData ] = useState(false);
  const [ isError, setIsError ] = useState(false);
  const [ errorMessage, setErrorMessage ] = useState('');
  const [ moviesGeneratedCount, setMoviesGeneratedCount ] = useState<MoviesGeneratedCountType>({
    countMovies: 0,
    maxMovies: 3,
  });
  const [moviesEmojizados, setMoviesEmojizados] = useState<MoviesEmojizadosType[]>([]);

  const { data: session } = useSession();

  const customSession = session as CustomSessionProps;

  // get first name the User
  const user_name = customSession?.user?.name?.split(' ')[0]!;

  const fetchMovies = useCallback(async () => {
    setIsLoadingData(true);
    try {
      const response = await api.post('/movies-emojis', {
        user_id: customSession?.userActive,
      });
      setMoviesGeneratedCount({
        countMovies: response.data.countMovies,
        maxMovies: response.data.maxMovies
      });
      setMoviesEmojizados(response.data.movies.data);
      setIsError(false);
    } catch (error) {
      setIsError(true);
      setErrorMessage('Ocorreu um erro ao buscar os filmes emojizados!');
    } finally {
      setIsLoadingData(false);
    }
  }, [customSession?.userActive]);

  useEffect(() => {
    if (customSession?.userActive) {
      fetchMovies();
    }
  }, [customSession?.userActive]);

  return (
    <>
      <Head>
        <title>Emojize seu filme preferido</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <main className={styles.main}>
        <Header
          moviesGeneratedCount={moviesGeneratedCount}
        />
        <h2 className={styles.title}>
          Olá <span>{user_name},</span> <br />
          Digite o nome do seu filme preferido
          e veja a mágica acontecer
        </h2>

        <Form
          listMoviesGenerated={fetchMovies}
          isLoading={loading}
          setErrorMessage={setErrorMessage}
          setIsError={setIsError}
          setLoading={setLoading}
        />

        {
          isError && <ErrorMessage message={errorMessage} />
        }

        <div className={styles.divider} />

          {
            isLoadingData ? (
              <div className={styles.isLoadingData}>
                <Loading />
              </div>
          ) : (
              moviesEmojizados.length > 0 && (
                <div className={styles.list}>
                  {
                    moviesEmojizados.map(({ data }) => (
                      <Card key={data.movieName} movieName={data.movieName} movieEmoji={data.movieEmojizado} />
                    ))
                  }
                </div>
              )
            )
          }
      </main>
    </>
  )
};


export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const session = await getSession({ req });

  const customSession = session as CustomSessionProps;

  if (!customSession?.userActive) {
    return {
      redirect: {
        destination: '/signin',
        permanent: false,
      }
    }
  }

  return {
    props: {}
  };
}
