import Head from "next/head";
import Image from "next/image";
import headerStyles from '@/styles/SignIn.module.scss';
import styles from '@/styles/PrivacyPolicy.module.scss';

export default function PrivacyPolicy() {
	return (
		<>
			<Head>
				<title>Login - Emojize seu filme preferido</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/icon.ico" />
			</Head>
			<header className={headerStyles.header}>
				<Image
					src="./Logo.svg"
					width={168}
					height={32}
					alt="Logo"
				/>
			</header>
			<main className={headerStyles.main}>
				<div>
					<h1>
						Política de privacidade {'\n'}
					</h1>
					<p className={styles.text}>
						Esta política de privacidade descreve como as informações pessoais são coletadas, usadas e compartilhadas quando você usa a nossa aplicação.
					</p>

					<h2 className={styles.subTitle}>
						Coleta de informações pessoais
					</h2>

					<p className={styles.text}>
						Quando você usa a nossa aplicação, podemos coletar as seguintes informações pessoais:
						Nome e endereço de e-mail fornecidos durante o processo de autenticação com o Google.
						Informações de localização, se você permitir o acesso à sua localização.
					</p>
					<h2 className={styles.subTitle}>
						Uso das informações pessoais {'\n'}
					</h2>
					<p className={styles.text}>
						As informações pessoais coletadas pela nossa aplicação são usadas para os seguintes propósitos:

						Para autenticar sua conta com o Google.

						Para fornecer os serviços solicitados por você.

						Para melhorar e personalizar a sua experiência com a nossa aplicação.
					</p>

					<h2 className={styles.subTitle}>
						Compartilhamento de informações pessoais
					</h2>
					<p className={styles.text}>
						Não compartilhamos suas informações pessoais com terceiros, exceto quando exigido por lei ou quando necessário para fornecer os serviços solicitados por você.
					</p>

					<h2 className={styles.subTitle}>
						Segurança {'\n'}
					</h2>
					<p className={styles.text}>
						Tomamos medidas razoáveis para proteger suas informações pessoais contra acesso não autorizado, alteração ou destruição.
					</p>
					<h2 className={styles.subTitle}>
						Alterações nesta política de privacidade
					</h2>
					<p className={styles.text}>
						Podemos atualizar esta política de privacidade de tempos em tempos. A versão mais recente sempre estará disponível na nossa aplicação.
					</p>
					<h2 className={styles.subTitle}>
						Contato
					</h2>
					<p className={styles.text}>
						Se você tiver alguma dúvida ou preocupação sobre esta política de privacidade, entre em contato conosco em <a href="">rodrigoalves.dev.js@gmail.com</a>
					</p>	
				</div>		
			</main>
		</>
	)
}